### ISSUE TITLE
Python documentation

### ISSUE THREAD

**Issue by rodrigondec** [dcrbrdev/JackBot#9]
Our python modules and files are not documented 😱😱😱

###  Tasks
- [ ] Create docstrings for bot module
  - [ ] `bot/core.py`
  - [ ] `bot/jack.py`
- [ ] Create docstring for sws module
  - [ ] `sws/message.py`
  - [ ] `sws/client.py`
